app = "ark-touchup-api"
primary_region = "yyz"

[build]
  # Fly will use your Dockerfile by default

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    soft = 25
    hard = 50

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "15s"
    grace_period = "30s"
    method = "GET"
    path = "/healthz"
    protocol = "http"
    timeout = "2s"
